In [3]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [14]:
np.array(((np.ones(20)*2)**(np.arange(1,21)))/np.arange(1,21))

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [18]:
np.sum(((np.ones(6)*0.1)**(np.arange(6)*3))*((np.ones(6)*0.2)**(np.arange(6)*4)))

1.00000160000256

In [20]:
sum([(0.1**(3*i))*(0.2**(4*i)) for i in range(6)])

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [37]:
zero_matrix = np.zeros((8,8))
zero_matrix[::2,::2] = 1
zero_matrix[1::2,1::2] = 1

In [38]:
zero_matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [123]:
X = np.random.random((5, 2))
ans = np.concatenate((np.sqrt(X[:,0]**2 + X[:,1]**2).reshape(5,1),np.arctan(X[:,1]/X[:,0]).reshape(5,1)),axis=1)

In [124]:
ans

array([[1.11200399, 0.86551838],
       [1.07731434, 1.18713352],
       [0.79092322, 1.50044643],
       [0.9617909 , 1.40533333],
       [0.89532381, 0.06807042]])

In [125]:
print(X)

[[0.72085157 0.84671476]
 [0.40325976 0.99899337]
 [0.05559548 0.78896685]
 [0.15841564 0.94865495]
 [0.89325033 0.06089801]]


In [131]:
ans[0,0]*np.sin(ans[0,1])

0.8467147598522402

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [171]:
X = np.random.random((10, 10))
ans = np.unravel_index(np.argmax(X),X.shape)
print(ans)

(4, 2)


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [177]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
ans = X[np.argmin(np.sqrt(np.sum((X-y)**2,axis=1)))]
print(ans)

[0.15462622 0.64630199]


In [178]:
distance = [np.sqrt((X[i,0]-y[0,0])**2 +(X[i,1]-y[0,1])**2) for i in range(10)]

In [179]:
X[np.argmin(distance)]

array([0.15462622, 0.64630199])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [175]:
def f(x):
    if x < 0:
        return x**2 + 2*x + 6
    if x >= 0 and x <= 2:
        return x + 6
    if x >= 2:
        return x**2 + 4*x - 4
x_dots = np.linspace(-3,3,20)   
ans = list(map(f,x_dots))

In [176]:
ans

[9.0,
 7.836565096952908,
 6.872576177285318,
 6.10803324099723,
 5.542936288088643,
 5.177285318559557,
 5.011080332409972,
 5.044321329639889,
 5.2770083102493075,
 5.7091412742382275,
 6.157894736842105,
 6.473684210526315,
 6.789473684210526,
 7.105263157894736,
 7.421052631578947,
 7.7368421052631575,
 8.423822714681439,
 11.08310249307479,
 13.941828254847643,
 17.0]

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [188]:
X = np.random.random((10, 10))
X = X - np.mean(X,axis=1).reshape(10,1)
np.mean(X,axis=1)

array([-1.11022302e-17, -3.33066907e-17,  1.22124533e-16, -2.22044605e-17,
       -2.22044605e-17, -5.55111512e-17,  0.00000000e+00, -6.66133815e-17,
        7.77156117e-17,  3.33066907e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [201]:
X = np.random.normal(loc=5, scale=2., size=1000)
mean = np.mean(X)
var = np.mean((X - mean)**2)
print(mean,var)

4.953450351621678 3.6602091627445827


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [211]:
X = np.fromfunction(lambda i,j:np.where(i+j<=4,i+j,(i+j)%5), (5,5), dtype=int)

In [212]:
X

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [278]:
np.random.seed(42)
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 4, 3, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [279]:
np.random.seed(42)
def sample1(x, c):
    assert len(x) > 0
    s = np.sum(x)
    x_matrix = np.stack([np.array(x)]*c,axis=0)
    cum_sum_matr = np.stack([np.cumsum(x)]*c,axis=0)
    val_vec = s * np.random.random((5,1))
    logical_m = cum_sum_matr >= val_vec
    res = list(np.argmax(logical_m, axis=1))
    return res

sample1([50, 3, 1, 7, 20], 5)  

[0, 4, 3, 0, 0]